### ISSUE TITLE
WKIK網址變了

### ISSUE THREAD

**Issue by Copanda** [TimWei/ZooeyPeroPero#1]
本來想自己更新可是跑開發板一直跑不出來也不知道如何簡單轉成EXE

**Comment by Copanda** [comment]
已自己轉成EXE成功了

**Comment by TimWei** [comment]
我稍會更新下WIKI網址

感謝回報

**Comment by TimWei** [comment]
@Copanda 

你重新拉取下代碼，將Wiki URL跟偵測之字段，獨立配置於config.json文件了

之後要自行更改配置應該簡單些
